namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: fundsan/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi

ContainerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz